"""empty message

Revision ID: 88e9d3e3c5fc
Revises: 8e0402c9e1fc
Create Date: 2021-06-29 17:04:41.994495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e9d3e3c5fc'
down_revision = '8e0402c9e1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newdocuments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newdocuments')
    # ### end Alembic commands ###
